#manipulator:
#  kinematics_solver: ur_kinematics/UR3eKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
manipulator:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Manipulation1 #Distance, Speed, Manipulation1, Manipulation2
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.01 #0.005
